### ISSUE TITLE
Item 새 클래스 작성 중 궁금증

### ISSUE THREAD

**Issue by DuhyunKR** [ICCAS2024-Helper/facialFit-backend#17]
<img width="309" alt="image" src="https://github.com/ICCAS2024-Helper/facialFit-backend/assets/153938155/68216924-b133-4b7f-bc91-4dc13d650584">

User 클래스랑 비슷한 형식으로 작성해야되나요?

**Comment by SinnoLn** [comment]
예 위처럼 작성하시면 됩니다. 
근데 각 아이템을 여러개 구매할 수 있게 할건가요?
quantity field가 있어서요

**Comment by DuhyunKR** [comment]
아 이거는 예로 작성했는데 수량은 1개로 지정할려고요!
