### ISSUE TITLE
권한 오류

### ISSUE THREAD

**Issue by DuhyunKR** [ICCAS2024-Helper/facialFit-backend#18]
<img width="445" alt="image" src="https://github.com/ICCAS2024-Helper/facialFit-backend/assets/153938155/7f1d0a71-e7d3-4182-aef0-a184b6c3c842">

**Comment by SinnoLn** [comment]
뭘할때 권한이 거부되는건가요? 일단 권한을 다시 줬는데 같은 오류가 뜨는지 확인해보실래요?

**Comment by DuhyunKR** [comment]
넵 커밋할려고 하는데 권한 오류가 나타나더라구요 다시 커밋해볼게요!

**Comment by SinnoLn** [comment]
넵 또 오류나면 알려주세요
