### ISSUE TITLE
403 에러

### ISSUE THREAD

**Issue by DuhyunKR** [ICCAS2024-Helper/facialFit-backend#4]
<img width="794" alt="화면 캡처 2024-06-02 234510" src="https://github.com/ICCAS2024-Helper/facialFit-backend/assets/153938155/049e27f3-283e-4bb4-a3c2-ca84627d13b4">

-내용1:API 만들려고 해서 테스트로 실행해보니깐 403에러가 뜨는데 혹시 이유를 알수있을까요

**Comment by SinnoLn** [comment]
test api는 말그대로 swagger에 뜨나 확인해본거라 제대로 동작하지 않을거에요.. 
제가 회원가입 api 간단하게 만들어서 다시 커밋할테니까 한번 그거 봐보실래요?

**Comment by DuhyunKR** [comment]
넵 알겠습니다
